---
title: "Hogan 2015/2017 Sensitivity Analysis: How many parents to sample?"
output:
  html_notebook:
    theme: united
    toc: yes
editor_options: 
  chunk_output_type: inline
---

```{r setup, include=FALSE}
library(coin)
library(MASS)
library(scales)
library(tidyverse)
library(leaflet)
library(lubridate)
library(ggExtra)

knitr::opts_chunk$set(out.width = "100%", fig.width = 10)
```

# Background

# Read in data

```{r}
(hogan_paired_15_17_filter <- read_csv("hogan_paired_15_17_filter.csv"))

(hogan_paired_15_17_filter_parents <- read_csv("hogan_paired_15_17_filter_parents.csv") %>% 
    filter(SEX != "?")
)
```

# Sample Sizes

```{r}
hogan_paired_15_17_filter_parents %>% 
  count(origin, SEX) %>% 
  spread(origin, n)
```

# Calculate RS with all samples

```{r}
rs_15_17_0 <- hogan_paired_15_17_filter_parents %>%
  group_by(origin, SEX) %>% 
  summarise(RS = mean(n, na.rm = TRUE))

rs_15_17_0 %>%
  mutate(RS = round(RS, 3)) %>% 
  spread(origin, RS)
```

# With a reduced sample size

```{r}
rrs_15_17_0_sub <- sapply(seq(from = 100, to = 1700, by = 100), function(samp_n) {
  sapply(1:100, function(rep_n) {
    hogan_paired_15_17_filter_parents %>%
      group_by(origin, SEX) %>%
      sample_n(samp_n, replace = FALSE) %>%
      summarise(RS = mean(n, na.rm = TRUE)) %>%
      spread(origin, RS) %>% 
      group_by(SEX) %>% 
      summarise(RRS = Hatchery / Natural) %>% 
      ungroup() %>% 
      mutate(samp_n = samp_n,
             rep_n = rep_n)
  }, simplify = FALSE) %>% 
    dplyr::bind_rows()
}, simplify = FALSE) %>%
  bind_rows()
```

## Plot

```{r}
rrs_15_17_0_sub %>% 
  ggplot(aes(x = samp_n, y = RRS)) +
  geom_point(alpha = 0.1) + 
  stat_density_2d(aes(fill = after_stat(nlevel)), geom = "polygon") +
  ylim(c(0, 1)) +
  facet_grid(. ~ SEX) +
  scale_fill_viridis_c()+
  theme_bw()
```

